### ISSUE TITLE
Chinese translations appearing out of nowhere in the Russian version of the application

### ISSUE THREAD

**Issue by Quanor** [TDesktop-x64/Localization#129]
Not really an important translation of the phrases above, but I came across this problem in "Extreme Settings". 
The following item with the name "使用正體中文翻譯訊息" is displayed (Highlighted in green in the screenshot)

By a strange coincidence, I do know Chinese, and I can tell you that this phrase translates into English as "Translate messages using proper Chinese"

As far as I understand, this problem is caused by one of the translations, and is most likely a comment for the Chinese translators. I couldn't find it in the Chinese translation, so I don't understand where this line comes from. It is not unimportant to mention that I used the Russian translation for the app

![изображение](https://user-images.githubusercontent.com/88768830/217589313-9bdc7bf7-ad49-444e-aaa8-046f58e47e93.png)

**Comment by deptyped** [comment]
This item is displayed in all localizations. A new localization key [lng_settings_translate_to_tc](https://github.com/TDesktop-x64/tdesktop/blob/1a1da57a663adbf48c450a660f03e2c3d89d0110/Telegram/Resources/langs/lang.strings#L3729) has been added, just not added to the localization files yet.

**Comment by c0re100** [comment]
> This item is displayed in all localizations. A new localization key [lng_settings_translate_to_tc](https://github.com/TDesktop-x64/tdesktop/blob/1a1da57a663adbf48c450a660f03e2c3d89d0110/Telegram/Resources/langs/lang.strings#L3729) has been added, just not added to the localization files yet. I suggest displaying this option only if the user is using Chinese, in other localizations it makes no sense.

I suggest displaying this option only if the user is using Chinese < Yes, it's planned.

**Comment by Quanor** [comment]
> > This item is displayed in all localizations. A new localization key [lng_settings_translate_to_tc](https://github.com/TDesktop-x64/tdesktop/blob/1a1da57a663adbf48c450a660f03e2c3d89d0110/Telegram/Resources/langs/lang.strings#L3729) has been added, just not added to the localization files yet. I suggest displaying this option only if the user is using Chinese, in other localizations it makes no sense.
> 
> I suggest displaying this option only if the user is using Chinese < Yes, it's planned.

In that case, I think I'll close this issue so it doesn't bother us all. The important thing is that you know
